net:
  port: 40003
spec:
  priv_key: "3NDY63fQYrRMHbYsFUZHAnqTGagVNMnWQrRBXbCqgxJ5"
  log_file:
    - type      : "ScribeJSON"
      path      : "logs/node-3.log"
      severity  : "Debug"
      verbosity : "V2"
  db_name: "db/db3"
