port: 40004
priv_key: "FJgB8hGT34QpemNc4Hgc9hkwKScTyugXtLtL19xB1gpJ"
spec:
  log_file:
    - type      : "ScribeJSON"
      path      : "logs/node-4.log"
      severity  : "Debug"
      verbosity : "V2"
  db_name: "db/db4"
