net:
  port: 40002
spec:
  priv_key: "6aNgwvijioMN98GFPbQUrJYNPRvh43mcGTCRi4U5eKCX"
  log_file:
    - type      : "ScribeJSON"
      path      : "logs/node-2.log"
      severity  : "Debug"
      verbosity : "V2"
  db_name: "db/db2"
