---
kind: pipeline
name: default

steps:
- name: build-hschain-ghc883
  image: nixos/nix:2.3.4
  privileged: true
  network_mode: host
  environment:
    DRONE_GITHUB_PULL_KEY:
      from_secret: drone_github_pull_key
    NIX_CACHE_KEY:
      from_secret: nix_cache_key
    NIX_CACHE_SIGNING_KEY:
      from_secret: nix_cache_signing_key
  commands:
  - apk add --no-cache git bash openssh-client
  - source ./nix/setup_ssh_ci.sh
  - "echo -n \"$${NIX_CACHE_SIGNING_KEY}\" > \"$${HOME}/nix-cache-key.sec\""
  - "chmod 400 \"$${HOME}/nix-cache-key.sec\""
  - cd nix
  - ./build-ci.sh --argstr ghc ghc883  --arg useSodium true  --arg isBench true

- name: build-hschain-ghc865
  image: nixos/nix:2.3.4
  privileged: true
  network_mode: host
  environment:
    DRONE_GITHUB_PULL_KEY:
      from_secret: drone_github_pull_key
    NIX_CACHE_KEY:
      from_secret: nix_cache_key
    NIX_CACHE_SIGNING_KEY:
      from_secret: nix_cache_signing_key
  commands:
  - apk add --no-cache git bash openssh-client
  - source ./nix/setup_ssh_ci.sh
  - "echo -n \"$${NIX_CACHE_SIGNING_KEY}\" > \"$${HOME}/nix-cache-key.sec\""
  - "chmod 400 \"$${HOME}/nix-cache-key.sec\""
  - cd nix
  - ./build-ci.sh --argstr ghc ghc865  --arg useSodium true  --arg isBench true

- name: build-hschain-cryptonite
  image: nixos/nix:2.3.4
  privileged: true
  network_mode: host
  environment:
    DRONE_GITHUB_PULL_KEY:
      from_secret: drone_github_pull_key
    NIX_CACHE_KEY:
      from_secret: nix_cache_key
    NIX_CACHE_SIGNING_KEY:
      from_secret: nix_cache_signing_key
  commands:
  - apk add --no-cache git bash openssh-client
  - source ./nix/setup_ssh_ci.sh
  - "echo -n \"$${NIX_CACHE_SIGNING_KEY}\" > \"$${HOME}/nix-cache-key.sec\""
  - "chmod 400 \"$${HOME}/nix-cache-key.sec\""
  - cd nix
  - ./build-ci.sh --argstr ghc ghc883  --arg useSodium false  --arg isBench true

- name: build-hschain-ghcjs
  image: nixos/nix:2.3.4
  privileged: true
  network_mode: host
  commands:
  - apk add --no-cache git bash openssh-client
  - source ./nix/setup_ssh_ci.sh
  - "echo -n \"$${NIX_CACHE_SIGNING_KEY}\" > \"$${HOME}/nix-cache-key.sec\""
  - "chmod 400 \"$${HOME}/nix-cache-key.sec\""
  - cd nix
  - ./build-ci.sh --argstr ghc ghcjs
  environment:
    DRONE_GITHUB_PULL_KEY:
      from_secret: drone_github_pull_key
    NIX_CACHE_KEY:
      from_secret: nix_cache_key
    NIX_CACHE_SIGNING_KEY:
      from_secret: nix_cache_signing_key

- name: dockerize-hschain
  image: nixos/nix:2.3.4
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  privileged: true
  network_mode: host
  depends_on:
#  - build-hschain-ghc84
  - build-hschain-ghc883
#  - build-hschain-ghcjs
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
    DRONE_GITHUB_PULL_KEY:
      from_secret: drone_github_pull_key
    NIX_CACHE_KEY:
      from_secret: nix_cache_key
    NIX_CACHE_SIGNING_KEY:
      from_secret: nix_cache_signing_key
  commands:
  - apk add --no-cache git bash openssh-client docker
  - source ./nix/setup_ssh_ci.sh
  - "echo -n \"$${NIX_CACHE_SIGNING_KEY}\" > \"$${HOME}/nix-cache-key.sec\""
  - "chmod 400 \"$${HOME}/nix-cache-key.sec\""
  - cd nix
  - ./build-docker-ci.sh

- name: telegram
  image: appleboy/drone-telegram
  depends_on:
  - dockerize-hschain
  settings:
    to:
      from_secret: telegram_id
    token:
      from_secret: telegram_token
    message: >
      {{build.status}}

      {{build.link}}

      ${DRONE_BUILD_EVENT} ${DRONE_PULL_REQUEST= }${DRONE_TAG= } to branch *{{commit.branch}}* by {{commit.author}}

      {{commit.message}}
  when:
    event: push
    status:
    - success
    - failure

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock

trigger:
  branch:
  - master
  cron:
    exclude:
    - nightly

---
kind: pipeline
name: tag

steps:
- name: build-hschain
  image: nixos/nix
  privileged: true
  network_mode: host
  environment:
    DRONE_GITHUB_PULL_KEY:
      from_secret: drone_github_pull_key
    NIX_CACHE_KEY:
      from_secret: nix_cache_key
    NIX_CACHE_SIGNING_KEY:
      from_secret: nix_cache_signing_key
  commands:
  - apk add --no-cache git bash openssh-client
  - source ./nix/setup_ssh_ci.sh
  - "echo -n \"$${NIX_CACHE_SIGNING_KEY}\" > \"$${HOME}/nix-cache-key.sec\""
  - "chmod 400 \"$${HOME}/nix-cache-key.sec\""
  - cd nix
  - ./build-ci.sh

- name: dockerize-hschain
  image: nixos/nix
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  privileged: true
  network_mode: host
  depends_on:
  - build-hschain
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
    DRONE_GITHUB_PULL_KEY:
      from_secret: drone_github_pull_key
    NIX_CACHE_KEY:
      from_secret: nix_cache_key
    NIX_CACHE_SIGNING_KEY:
      from_secret: nix_cache_signing_key
  commands:
  - apk add --no-cache git bash openssh-client docker
  - source ./nix/setup_ssh_ci.sh
  - "echo -n \"$${NIX_CACHE_SIGNING_KEY}\" > \"$${HOME}/nix-cache-key.sec\""
  - "chmod 400 \"$${HOME}/nix-cache-key.sec\""
  - cd nix
  - ./build-docker-ci.sh

- name: telegram
  image: appleboy/drone-telegram
  depends_on:
  - dockerize-hschain
  settings:
    to:
      from_secret: telegram_id
    token:
      from_secret: telegram_token
    message: >
      {{build.status}}

      {{build.link}}

      ${DRONE_BUILD_EVENT} ${DRONE_PULL_REQUEST= }${DRONE_TAG= } to branch *{{commit.branch}}* by {{commit.author}}

      {{commit.message}}

      build time is {{buildtime build.started}}
  when:
    event: push
    status:
    - success
    - failure

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock

trigger:
  event:
  - tag

---
kind: pipeline
name: cron

steps:
- name: build-hschain-nightly
  image: nixos/nix
  privileged: true
  network_mode: host
  environment:
    DRONE_GITHUB_PULL_KEY:
      from_secret: drone_github_pull_key
    NIX_CACHE_KEY:
      from_secret: nix_cache_key
    NIX_CACHE_SIGNING_KEY:
      from_secret: nix_cache_signing_key
  commands:
  - apk add --no-cache git bash openssh-client
  - source ./nix/setup_ssh_ci.sh
  - "echo -n \"$${NIX_CACHE_SIGNING_KEY}\" > \"$${HOME}/nix-cache-key.sec\""
  - "chmod 400 \"$${HOME}/nix-cache-key.sec\""
  - cd nix
  - ./build-ci.sh --arg isCoreLint true

- name: telegram
  image: appleboy/drone-telegram
  depends_on:
  - build-hschain-nightly
  settings:
    to:
      from_secret: telegram_id
    token:
      from_secret: telegram_token
    message: >
      {{build.status}}

      {{build.link}}

      ${DRONE_BUILD_EVENT} ${DRONE_PULL_REQUEST= }${DRONE_TAG= } to branch *{{commit.branch}}* by {{commit.author}}

      {{commit.message}}

      build time is {{buildtime build.started}}
  when:
    status:
    - success
    - failure

trigger:
  cron:
  - nightly
