clone:
  git:
    image: plugins/git:next
    pull: true

pipeline:
  restore-cache:
    image: plugins/s3-cache:1
    pull: true
    endpoint: https://ams3.digitaloceanspaces.com
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    restore: true

  build:
    image: haskell:8.2.2
    network_mode: host
    commands:
    - stack --stack-root $PWD/.stack --system-ghc test

  rebuild-cache:
    image: plugins/s3-cache:1
    pull: true
    endpoint: https://ams3.digitaloceanspaces.com
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    rebuild: true
    mount:
    - .stack
    when:
      event: push

  flush_cache:
    image: plugins/s3-cache:1
    pull: true
    endpoint: https://ams3.digitaloceanspaces.com
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    flush: true
    flush_age: 14

  telegram:
    image: appleboy/drone-telegram
    token: $PLUGIN_TOKEN
    to: $PLUGIN_TO
    secrets: [ plugin_token, plugin_to ]
    message: >
      {{build.status}}

      {{build.link}}

      ${DRONE_BUILD_EVENT} ${DRONE_PULL_REQUEST= } to branch *{{commit.branch}}* by {{commit.author}}

      {{commit.message}}

      build time is {{buildtime build.started}}
    when:
      status: [ success, failure ]

branches: [ master ]
