pipeline:
  restore-cache:
    image: plugins/s3-cache:1
    pull: true
    endpoint: https://ams3.digitaloceanspaces.com
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    restore: true

  build:
    image: haskell:8.2.2
    network_mode: host
    commands:
    - if git log -1 --pretty=%B |grep -i -q '\[clear cache\]'; then stack --stack-root $PWD/.stack --system-ghc clean; fi
    - stack --stack-root $PWD/.stack --system-ghc test

  rebuild-cache:
    image: plugins/s3-cache:1
    pull: true
    endpoint: https://ams3.digitaloceanspaces.com
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    rebuild: true
    mount:
    - .stack
    - .stack-work
    when:
      event: push
      status: [ success, failure ]

  telegram:
    image: appleboy/drone-telegram
    token: $PLUGIN_TOKEN
    to: $PLUGIN_TO
    secrets: [ plugin_token, plugin_to ]
    when:
      status: [ failure ]

branches: master
