---
kind: pipeline
name: default

steps:
- name: build-thundemint
  image: nixos/nix
  privileged: true
  network_mode: host
  environment:
    DRONE_GITHUB_PULL_KEY:
      from_secret: drone_github_pull_key
    NIX_CACHE_KEY:
      from_secret: nix_cache_key
    NIX_CACHE_SIGNING_KEY:
      from_secret: nix_cache_signing_key
  commands:
  - apk add --no-cache git bash openssh-client
  - source ./nix/setup_ssh_ci.sh
  - "echo -n \"$${NIX_CACHE_SIGNING_KEY}\" > \"$${HOME}/nix-cache-key.sec\""
  - "chmod 400 \"$${HOME}/nix-cache-key.sec\""
  - cd nix
  - ./build-ci.sh

- name: build-thundemint-ghc86
  image: nixos/nix
  privileged: true
  network_mode: host
  commands:
  - apk add --no-cache git bash openssh-client
  - source ./nix/setup_ssh_ci.sh
  - "echo -n \"$${NIX_CACHE_SIGNING_KEY}\" > \"$${HOME}/nix-cache-key.sec\""
  - "chmod 400 \"$${HOME}/nix-cache-key.sec\""
  - cd nix
  - ./build-ci.sh --argstr ghc ghc863
  environment:
    DRONE_GITHUB_PULL_KEY:
      from_secret: drone_github_pull_key
    NIX_CACHE_KEY:
      from_secret: nix_cache_key
    NIX_CACHE_SIGNING_KEY:
      from_secret: nix_cache_signing_key

- name: build-thundemint-ghcjs
  image: nixos/nix
  privileged: true
  network_mode: host
  commands:
  - apk add --no-cache git bash openssh-client
  - source ./nix/setup_ssh_ci.sh
  - "echo -n \"$${NIX_CACHE_SIGNING_KEY}\" > \"$${HOME}/nix-cache-key.sec\""
  - "chmod 400 \"$${HOME}/nix-cache-key.sec\""
  - cd nix
  - ./build-ci.sh --argstr ghc ghcjs
  environment:
    DRONE_GITHUB_PULL_KEY:
      from_secret: drone_github_pull_key
    NIX_CACHE_KEY:
      from_secret: nix_cache_key
    NIX_CACHE_SIGNING_KEY:
      from_secret: nix_cache_signing_key

- name: build-thundemint-nightly
  image: nixos/nix
  privileged: true
  network_mode: host
  commands:
  - apk add --no-cache git bash openssh-client
  - source ./nix/setup_ssh_ci.sh
  - "echo -n \"$${NIX_CACHE_SIGNING_KEY}\" > \"$${HOME}/nix-cache-key.sec\""
  - "chmod 400 \"$${HOME}/nix-cache-key.sec\""
  - cd nix
  - echo 'this is cron job build example step'
  environment:
    DRONE_GITHUB_PULL_KEY:
      from_secret: drone_github_pull_key
    NIX_CACHE_KEY:
      from_secret: nix_cache_key
    NIX_CACHE_SIGNING_KEY:
      from_secret: nix_cache_signing_key

- name: telegram
  image: appleboy/drone-telegram
  depends_on:
  - build-thundemint
  - build-thundemint-ghc86
  - build-thundemint-ghcjs
  settings:
    to:
      from_secret: telegram_id
    token:
      from_secret: telegram_token
    message: >
      {{build.status}}

      {{build.link}}

      ${DRONE_BUILD_EVENT} ${DRONE_PULL_REQUEST= }${DRONE_TAG= } to branch *{{commit.branch}}* by {{commit.author}}

      {{commit.message}}

      build time is {{buildtime build.started}}
  when:
    status:
    - success
    - failure

trigger:
  branch:
  - master

---
kind: pipeline
name: cron

steps:
- name: build-thundemint-nightly
  image: nixos/nix
  privileged: true
  network_mode: host
  when:
    event:
    - push
    - pull_request
  environment:
    DRONE_GITHUB_PULL_KEY:
      from_secret: drone_github_pull_key
    NIX_CACHE_KEY:
      from_secret: nix_cache_key
    NIX_CACHE_SIGNING_KEY:
      from_secret: nix_cache_signing_key
  commands:
  - apk add --no-cache git bash openssh-client
  - source ./nix/setup_ssh_ci.sh
  - "echo -n \"$${NIX_CACHE_SIGNING_KEY}\" > \"$${HOME}/nix-cache-key.sec\""
  - "chmod 400 \"$${HOME}/nix-cache-key.sec\""
  - cd nix
  - echo "this is cron nightly build"

- name: telegram
  image: appleboy/drone-telegram
  depends_on:
  - build-thundemint-nightly
  settings:
    to:
      from_secret: telegram_id
    token:
      from_secret: telegram_token
    message: >
      {{build.status}}

      {{build.link}}

      ${DRONE_BUILD_EVENT} ${DRONE_PULL_REQUEST= }${DRONE_TAG= } to branch *{{commit.branch}}* by {{commit.author}}

      {{commit.message}}

      build time is {{buildtime build.started}}
  when:
    status:
    - success
    - failure

trigger:
  cron:
  - nightly
