nodePort: 50003
nspecPrivKey: "3NDY63fQYrRMHbYsFUZHAnqTGagVNMnWQrRBXbCqgxJ5"
nspecLogFile:
  - type      : "ScribeJSON"
    path      : "logs/node-3.log"
    severity  : "Debug"
    verbosity : "V2"
nspecDbName: "db/db3"
