nodePort: 50001
nspecPrivKey: "3d6iUCAa2WQw1ePDtdp2qgji22PRmSrZ8zxhCeMRMBqX"
nspecLogFile: []
# - type      : "ScribeJSON"
#   path      : "logs/node-1.log"
#   severity  : "Debug"
#   verbosity : "V2"
nspecDbName: "db/db1"
