- hosts: localhost
  gather_facts: false
  become: true

  tasks:

  - name: Copy configs
    copy:
      src: "configs"
      dest: /root/

  - name: Log into private registry
    tags: registry
    docker_login:
      registry: "{{ registry_host }}"
      username: "{{ registry_user }}"
      password: "{{ registry_pass }}"

  - name: Start dioxane
    docker_compose:
      project_name: hschain
      pull: yes
      definition:
        version: '2.4'
        services:
          dio1:
            image: "{{ docker_image }}"
            container_name: dio1
            command: ["hschain-dioxane-node","--max-h","100","/configs/common.yaml","/configs/local1.yaml"]
            network_mode: host
            environment:
              GHCRTS: '-N8 -qn1 -A8m -n1m -qb1 -I0'
            volumes:
            - /root/configs:/configs
            - /root/logs:/logs
            restart: "no"
          dio2:
            image: "{{ docker_image }}"
            container_name: dio2
            command: ["hschain-dioxane-node","--max-h","100","/configs/common.yaml","/configs/local2.yaml"]
            network_mode: host
            environment:
              GHCRTS: '-N8 -qn1 -A8m -n1m -qb1 -I0'
            volumes:
            - /root/configs:/configs
            - /root/logs:/logs
            restart: "no"
          dio3:
            image: "{{ docker_image }}"
            container_name: dio3
            command: ["hschain-dioxane-node","--max-h","100","/configs/common.yaml","/configs/local3.yaml"]
            network_mode: host
            environment:
              GHCRTS: '-N8 -qn1 -A8m -n1m -qb1 -I0'
            volumes:
            - /root/configs:/configs
            - /root/logs:/logs
            restart: "no"
