nodeSeeds:
  - "127.0.0.1:40001"
  - "127.0.0.1:40002"
  - "127.0.0.1:40003"
  - "127.0.0.1:40004"
consensus:
  timeoutNewHeight  : 0
  timeoutProposal   : [125,100]
  timeoutPrevote    : [500,300]
  timeoutPrecommit  : [500,300]
#  timeoutEmptyBlock : !Int
#  incomingQueueSize : !Natural
network:
  gossipDelayBlocks : 5
