nodeSeeds:
  - "127.0.0.1:40001"
  - "127.0.0.1:40002"
  - "127.0.0.1:40003"
  - "127.0.0.1:40004"
consensus:
  timeoutNewHeight  : 100
  timeoutProposal   : [500,100]
  timeoutPrevote    : [500,100]
  timeoutPrecommit  : [500,100]
#  timeoutEmptyBlock : !Int
#  incomingQueueSize : !Natural
