---

- hosts: all
  gather_facts: no
  become: yes
  vars:
   key: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAxTdrmmj5vptkUmGKgqxCNTkX50rO42GUkO6FN4UYqglbVwHwVjUI2N0Sm7BEFibokBdSffbOXi45qGZGk0SP2TwyyvtKkMTfRdRmDLnptfJl2a2A7m3tAIeAVMyKVDR3KUkWuappGhEXvnxEQizRGH7EV9WekGatN4BPZTUc3b7SyU3UjrwM8z1CithmiaMOPZLGBGMBYuXR9HZllXBMJ2DUnCfrPzXd6D55KL/5e1bi1hOtyym1rmh1Fm9BYgD7opH6eBQeqPObOxoRPHYrGigiWg+YRf77xR8lPzVRFpKBHiwvrwVPJgVoFxvZ6UvQ4vGUt00ZQjyGTdbayH721Q== dmalkr@mjolnir"

  tasks:

  - name: Set authorized key
    authorized_key:
     user: "root"
     key: "{{ key }}"
