- hosts: all
  serial: 1

  tasks:

  - apt:
      name: "{{ item }}"
    with_items:
    - python3-boto3
    - python3-botocore

  - archive:
      path:
      - "/var/lib/docker/volumes/thundermint/_data/logs/{{ ansible_hostname }}"
      dest: "/tmp/{{ ansible_hostname }}.gz"

  - aws_s3:
      s3_url: https://ams3.digitaloceanspaces.com
      bucket: "{{ s3_bucket_name }}"
      mode: put
      ignore_nonexistent_bucket: true
      object: "{{ ansible_hostname }}.gz"
      src: "/tmp/{{ ansible_hostname }}.gz"
      rgw: true
      encrypt: false
      aws_access_key: "{{ s3_access_key }}"
      aws_secret_key: "{{ s3_secret_key }}"
