node:
  number    : 3
  count     : 4
  port      : 45004
  seeds     :
      - "127.0.0.1:45001"
  privKey   : "D2fpHM1JA8trshiUW8XPvspsapUvPqVzSofaK1MGRySd"
  validators:
    - "2K7bFuJXxKf5LqogvVRQjms2W26ZrjpvUjo5LdvPFa5Y"
    - "4NSWtMsEPgfTK25tCPWqNzVVze1dgMwcUFwS5WkSpjJL"
    - "3Fj8bZjKc53F2a87sQaFkrDas2d9gjzK57FmQwnNnSHS"
    - "D2fpHM1JA8trshiUW8XPvspsapUvPqVzSofaK1MGRySd"
  dbName  : "db/node-4"
coin:
   maxH:       10
   delay:      300
   deposit:    1000
   keys:       2000
   walletKeys: [1500,2000]
logs:
  logFiles :
    - type      : "ScribeJSON"
      path      : "logs/node-4.log"
      severity  : "Debug"
      verbosity : "V2"
  hostnameSuffix: "-node4"
  clusterId     : "stand"
