node:
  number    : 2
  count     : 4
  port      : 45003
  seeds     :
    - "127.0.0.1:45004"
  privKey   : "3Fj8bZjKc53F2a87sQaFkrDas2d9gjzK57FmQwnNnSHS"
  validators:
    - "2K7bFuJXxKf5LqogvVRQjms2W26ZrjpvUjo5LdvPFa5Y"
    - "4NSWtMsEPgfTK25tCPWqNzVVze1dgMwcUFwS5WkSpjJL"
    - "3Fj8bZjKc53F2a87sQaFkrDas2d9gjzK57FmQwnNnSHS"
    - "D2fpHM1JA8trshiUW8XPvspsapUvPqVzSofaK1MGRySd"
  dbName  : "db/node-3"
coin:
   maxH:       10
   delay:      300
   deposit:    1000
   keys:       2000
   walletKeys: [1000,1500]
logs:
  logFiles :
    - type      : "ScribeJSON"
      path      : "logs/node-3.log"
      severity  : "Debug"
      verbosity : "V2"
  hostnameSuffix: "-node3"
  clusterId     : "stand"
