nodePort: 40002
nspecPrivKey: "6aNgwvijioMN98GFPbQUrJYNPRvh43mcGTCRi4U5eKCX"
nspecLogFile:
  - type      : "ScribeJSON"
    path      : "logs/node-2.log"
    severity  : "Debug"
    verbosity : "V2"
nspecDbName: "db/db2"
